type WeatherElementType =
    | "temperature"
    | "perceived-temperature"
    | "wind-chill"
    | "leaf-temperature"
    | "soil-temperature"
    | "soil-moisture"
    | "solar-radiation"
    | "wind-speed"
    | "wind-gust"
    | "wind-direction"
    | "uv"
    | "evaporation"
    | "leaf-wetness"
    | "pressure"
    | "precipation-rate"
    | "shower-precipation"
    | "precipation"
    | "precipation-probability"
    | "humidity"
    | "cloudiness"
    | "sunshine"
    | "visibility"
    | "snow-height"
    | "weather-state"
    | "soil-ph";

export default WeatherElementType;
